

httpclient.connect.timeout=5000
httpclient.read.timeout=10000
httpclient.max.connections=10
httpclient.max.per.route=5
httpclient.proxy.enabled=false

httpclient.retry.count=3
httpclient.retry.delay=1000

date.time.format=yyyy-MM-dd HH:mm:ss

api.key=6fc1d71c084f467bb471c67d3f56b462
api.base.url=https://mf4ky4q37p.re.qweatherapi.com/v7/weather/now

api.id.url=https://mf4ky4q37p.re.qweatherapi.com/geo/v2/city/lookup
