<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.yao.learn</groupId>
  <artifactId>simple-net-weather-query-client</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>simple-net-weather-query-client</name>
  <url> </url>
  <modules>
    <module>dto</module>
    <module>clients</module>
    <module>parser</module>
    <module>exceptions</module>
    <module>main</module>
    <module>config</module>
  </modules>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit-jupiter-api.version>5.10.3</junit-jupiter-api.version>
    <httpclient5.version>5.5</httpclient5.version>
    <slf4j.version>2.0.17</slf4j.version>
    <log4j2.version>2.25.4</log4j2.version>
    <fastjson2.version>2.0.61</fastjson2.version>
    <config.version>1.0-SNAPSHOT</config.version>
    <disruptor.version>3.4.4</disruptor.version>
    <dto.version>1.0-SNAPSHOT</dto.version>
    <parser.version>1.0-SNAPSHOT</parser.version>
    <clients.version>1.0-SNAPSHOT</clients.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.yao.learn</groupId>
        <artifactId>clients</artifactId>
        <version>${clients.version}</version>
        <scope>compile</scope>
      </dependency>

      <dependency>
        <groupId>com.yao.learn</groupId>
        <artifactId>parser</artifactId>
        <version>${parser.version}</version>
        <scope>compile</scope>
      </dependency>

      <dependency>
        <groupId>com.yao.learn</groupId>
        <artifactId>dto</artifactId>
        <version>${dto.version}</version>
        <scope>compile</scope>
      </dependency>

      <dependency>
        <groupId>com.yao.learn</groupId>
        <artifactId>config</artifactId>
        <version>${config.version}</version>
        <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>${junit-jupiter-api.version}</version>
        <scope>test</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5 -->
      <dependency>
        <groupId>org.apache.httpcomponents.client5</groupId>
        <artifactId>httpclient5</artifactId>
        <version>${httpclient5.version}</version>
        <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${slf4j.version}</version>
        <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j2-impl -->
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-slf4j2-impl</artifactId>
        <version>${log4j2.version}</version>
        <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2 -->
      <dependency>
        <groupId>com.alibaba.fastjson2</groupId>
        <artifactId>fastjson2</artifactId>
        <version>${fastjson2.version}</version>
        <scope>compile</scope>
      </dependency>
      <!-- Source: https://mvnrepository.com/artifact/com.lmax/disruptor -->
      <dependency>
        <groupId>com.lmax</groupId>
        <artifactId>disruptor</artifactId>
        <version>${disruptor.version}</version>
        <scope>compile</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
